### ISSUE TITLE
Photos Scrolling with the arrow keys

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#101]
Now there is weirdness when scrolling with the arrow keys. It seems to be stuck in a loop of the photos visible on the page or perhaps the photos that have been viewed already.

**Comment by fryarludwig** [comment]
When I reversed the scroll direction, I forgot to update the class names of the next/prev page buttons, which are used by the arrow keys when they reach the first or last thumbnails in the overlay. This has been fixed, and was the main cause of this issue.

An additional issue I found while looking into this also allowed for a "loop" of sorts - when scrolling rapidly through the images, requests would return more slowly than they were made - allowing for pages to load out of order. I've added semaphore-like behavior that prevents the page from "scrolling" before receiving the expected response.

**Comment by AmberSJones** [comment]
Looks good now. Closing.
