### ISSUE TITLE
Check on/Add LR_Mendon_AA site

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#106]
There is a site missing from this list: http://data.iutahepscor.org/mdf/Data/Logan_River/
The site is LR_Mendon_AA. I'm not sure if there is actually a page for this site somewhere in the ether - if so, the link needs to be added here. If not, the page needs to be created and the link added.

**Comment by darksinge** [comment]
LR_Mendon_AA was on a list of sites to not display. I removed it from the list and it's now showing up on the website.
