### ISSUE TITLE
New Provo River sites

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#53]
Several sites need to be added to the Provo River watershed: 
PR_ST_C
PR_ST_BA
I will work on getting pictures for these sites.

There are also a repeater and a base station, but I think that we should not add those.

**Comment by marioscience** [comment]
These sites were added to Provo River.

**Comment by AmberSJones** [comment]
Great, I'm working on getting pictures, but I'm closing this issue.
