### ISSUE TITLE
Storm Drain Sites

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#54]
We have new sites in Red Butte Creek that are also a new type of site: storm drain. We need to add these sites to the Red Butte list- perhaps with their own section and each site needs its own site page. I can work on getting pictures of the sites. The sites are:
RB_CR_SD
RB_GIRF_SD
RB_FortD_SD
RB_Dent_SD

**Comment by marioscience** [comment]
Which variables do you want me to show for this site type?

**Comment by AmberSJones** [comment]
Flow, Discharge
Level, Water depth
Velocity, Velocity
Volume, Volume
WaterTemp_ISCO, Temperature

**Comment by marioscience** [comment]
Variables were added to Storm Drain sites.

**Comment by AmberSJones** [comment]
Great. Can you group the storm drain sites together and give them a heading (Storm Drain Sites) on this page http://django.uwrl.usu.edu/mdf/Data/Red_Butte/

**Comment by marioscience** [comment]
The sites were grouped and added heading. I moved the disclaimer to before the first heading so that it covers both the old heading and the storm drain heading.

**Comment by AmberSJones** [comment]
@horsburgh , will you look at this and see what you think? Could we keep all sites in the same box/table, just with a subheader?

**Comment by AmberSJones** [comment]
@horsburgh likes it, so I'm closing.
