### ISSUE TITLE
Update the Presentations/Posters Page

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#55]
We need to update the Presentations/Posters page with the following entries. The pdf files are loaded to the Google Drive Presentations folder. Note that we've  separated Presentations into 'Presentations at iUTAH Meetings' and 'Presentations at Professional Meetings'. All of the presentations currently on the page should fall under the 'Presentations at Professional Meetings' category.

@horsburgh and @Castronova , can you provide pdf files of your missing presentations (I didn't have your files for AGU and HIC)?

Presentations at iUTAH Meetings:

Jones, A.S. and Horsburgh, J.S. (2014)
Cyberinfrastructure for iUTAH RFA1: GAMUT Data Access and Beyond, Presented at: iUTAH Research Focus Area 1 Cyber Seminar Series, Online, December 2014.
iUTAH_RFA1_12-12-2014_ASJ.pdf

Jones, A.S., Horsburgh, J.S., Castronova, A.
Cyberinfrastructure Update. Presented at: iUTAH Fall All Hands Meeting, Salt Lake City UT, November 2014.
iUTAH_AHM_11-21-2014_ASJ.pdf

Horsburgh, J.S., Jones, A.S., Castronova, A.
Cyberinfrastructure Year 2 Advances. Presented at: iUTAH Symposium and All Hands Meeting, Logan UT, July 2014.
iUTAH_CI_Symposium_7-11-2014.pdf

Presentations at Professional Meetings:

Horsburgh, J.S., et al   (2014)
Information Requirements for Integrating Spatially Discrete, Feature-Based Earth Observations, Presented at: American Geophysical Union Fall Meeting, San Francisco CA, December 2014.

Horsburgh, J.S., Reeder, S.L., Jones, A.S.
ODM Tools Python: Open Source Software for Managing Continuous Sensor Data, Presented at: International Conference on Hydroinformatics, New York City NY, August 2014.

Jones, A.S., Horsburgh, J.S., 
Cyberinfrastructure for Data Management and Sharing within a Large-scale, Heterogeneous Sensor Network, Presented at: Mountain Observatories Global Fair and Workshop, Reno NV, July 2014
MountainObservatories2014_ASJ.pdf

Horsburgh, J.S., Jones, A.S., Reeder, S.L.
Automating Data Management and Sharing within a Large-Scale, Heterogeneous Sensor Network, Presented at: International Environmental Modelling and Software Symposium, San Diego CA, June 2014.
Horsburgh_iEMS_AutomatingDataManagement_iUTAH.pdf

Posters

Jones, A.S. and Horsburgh, J.S.
Implementation of Cyberinfrastructure and Data Management Workflow for a Large-Scale Sensor Network. Presented at: American Geophysical Union Fall Meeting, San Francisco CA, December 2014.
SensorWorkflow_AGU_ASJ_2014.pdf

Castronova, A., Jones, A.S., Horsburgh, J.S.
A Relational Model for Simulation Data to Promote Interdisciplinary Collaboration. Presented at: American Geophysical Union Fall Meeting, San Francisco CA, December 2014.

Jones, A.S., Horsburgh, J.S., Reeder, S.L., Meline, J.
ODM Tools Python: Open Source Software for Managing Environmental Sensor Data, Presented at: CUAHSI Field Data Solutions Virual Poster Session, Online, October 2014.
CUAHSI_FieldDataSolutions_ASJ.pdf

**Comment by marioscience** [comment]
In the last entry, the file is not in Google Drive. I'm using CUAHSI_FieldDataSolutionsPoster_ASJ.pdf instead, let me know if this is not correct.

**Comment by AmberSJones** [comment]
That's correct. I'll take a look at the update.

**Comment by AmberSJones** [comment]
@horsburgh and @Castronova , can you upload your final files from AGU and HIC to the Google drive (or send them to me) so we can get versions up on our website?

@marioscience , otherwise looks good. I'll keep it open until we get those additional files.

**Comment by horsburgh** [comment]
My Presentation from AGU is called: 2014_JSH_AGU_ODM2_12-17-2014.pptx.  It's in the Google folder.

**Comment by marioscience** [comment]
The files were added.

**Comment by AmberSJones** [comment]
I emailed you the file for 

Castronova, A., Jones, A.S., Horsburgh, J.S.
A Relational Model for Simulation Data to Promote Interdisciplinary Collaboration. Presented at: American Geophysical Union Fall Meeting, San Francisco CA, December 2014.

Please add that and we can get the issue closed.

**Comment by marioscience** [comment]
The file was added.
