### ISSUE TITLE
Update Data Collection Plan template

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#61]
There is a new template for data collection plans. It needs to be updated to this site: http://data.iutahepscor.org/mdf/Data/Data_Policy/

This sentence: "Here are links to an example Data Collection Plan and a blank Data Collection Plan template." should be linked to the updated template and the example Data Collection Plan removed.

This needs to be done urgently and pushed to production (you might want to make some of the other changes in the issue tracker so that we can do a more comprehensive push to production). I will send the updated template in an email.

**Comment by marioscience** [comment]
This file was updated.

**Comment by AmberSJones** [comment]
Great, thanks.
