### ISSUE TITLE
Add links to tutorial videos

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#66]
We need to add links to the data publication tutorial videos. We need to discuss where these should live (perhaps under Training Materials?) and how to link to them- a few folks have requested they be obvious on the MDF website.

**Comment by AmberSJones** [comment]
Ok, we've determined that these should be linked on the Training Materials page. On that page, create a header that says 'Data Publication Tutorials' and link to the four videos. We then need a link under 'Announcements' on the homepage. The videos are posted to the Cube in Public/Tutorials. @marioscience , can you do this?

**Comment by marioscience** [comment]
The tutorials were added.

**Comment by AmberSJones** [comment]
Great. We need a few things:

1. Add titles and text under the videos. Use the titles and text from this page: http://iutahepscor.org/data_modeling.shtml

2. Make this sentence on the homepage more prominent: 'Video tutorials are available here.' Maybe bold? Maybe larger font?

3. Move the Tutorial Videos to the top of the Training Materials page- above the 'Training Materials' section.

**Comment by marioscience** [comment]
Done. The changes are in the sandbox server. A push to production will happen after this is tested.

**Comment by AmberSJones** [comment]
Ok, looks good- push to production. Please send @pkdash  an email with the link to let him know when this is done.
