### ISSUE TITLE
Updates to the webpage

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#75]
We need to make a number of updates to the website. @jcaraballo17 , can you make some time for this? Let me know if you have any questions.

The following pages need to be updated for data.iutahepscor.org. The content is updated in the linked Google document.

- [x] Homepage: https://docs.google.com/document/d/1m4E31ygXoFX7WWt_FTZ6jJESuaJcDhHXiApuTR1OrlU/edit?pli=1

- [x] Software Development: https://docs.google.com/document/d/12LYwc4OkIcGI_Zb4H6h0Lasvgcomxuy4kjmShHB5Vhw/edit?pref=2&pli=1. The screenshots and images for this page are in the folder https://drive.google.com/drive/folders/0B9GfPV6J8U4XVlZlRm5DLWduY3c.

- [x] Hardware Development: https://docs.google.com/document/d/1Z7QwPlffqUAy-Fo4jeyTH4HuoQndEBxWvtcjHQ7ndxs/edit. The diagram needs to be updated- the image is in the pictures folder.

- [x] Documentation: https://docs.google.com/document/d/10bjsKWS81JzLoFlJORltH_qQAzQcnLSooYEB3VAoMKc/edit#
The files listed for posters and presentations are named in the document and can be found in the "Presentations" Google folder: https://drive.google.com/drive/folders/0B0mUuf2-qdlTNDZ3ZmlZbFVPSjg

- [ ] Training Materials: https://docs.google.com/document/d/1OSBEBGvrwI-UizoMvhwNSTqD9J2-rpNQV59IvU8r9Ec/edit?pli=1#heading=h.es5tr3bbnqbp
The files listed here are also in the "Presentations" Google folder.

- [ ] Data Policy and Publication: https://docs.google.com/document/d/1zPIV21-NX9wSMgP_pXBJ8D1XRLeNtxh84U4cKmml4RE/edit?pref=2&pli=1

**Comment by AmberSJones** [comment]
@jcaraballo17 Are all of the above complete? If so, let's close the issue.

**Comment by jcaraballo17** [comment]
Yes, all these changes have been applied.

**Comment by AmberSJones** [comment]
Thanks, @jcaraballo17 !
