### ISSUE TITLE
Sparkline plots not updating

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#76]
Looks like it has been some time (I'm embarrassed how long) since our sparkline plots have been updating. We need to get this addressed.
![image](https://cloud.githubusercontent.com/assets/5023186/17001360/e9d4ad16-4e83-11e6-9779-114b477395f2.png)

**Comment by AmberSJones** [comment]
@fryarludwig is this addressed yet?

**Comment by jcaraballo17** [comment]
@AmberSJones This will be updated when I run the Data Parser script.

**Comment by AmberSJones** [comment]
Great, thanks @jcaraballo17

**Comment by jcaraballo17** [comment]
Deployed the data parser changes @fryarludwig made and set up the scheduler to run each day as it was setup before.

**Comment by AmberSJones** [comment]
Seems to be working well. Closing.
