### ISSUE TITLE
New sites need to be added

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#77]
There are a number of new sites for which we need new landing pages with metadata and sparkline plots.

Logan River:
LR_RH_SD and LR_SC_SC need to be added as 'Storm Drain' sites 
BSF_CONF_BA needs to be added as an aquatic site
to this page: http://data.iutahepscor.org/mdf/Data/Logan_River/

Provo River:
PR_WD_BA needs to be added as an aquatic site
PR_SageCreek_canal and PR_Flood_canal need to be added as 'Canal' sites
to this page: http://data.iutahepscor.org/mdf/Data/Provo_River/

Red Butte Creek:
RB_900W_BA, RB_1300E_A, and RB_LKF_A need to be added as aquatic sites
to this page: http://data.iutahepscor.org/mdf/Data/Red_Butte/

**Comment by fryarludwig** [comment]
These have been added in the codebase. The latest version will need to be pulled and the DataParser run before the sites will load properly.

**Comment by AmberSJones** [comment]
@fryarludwig Thanks. Are you handling the pulling and running of the DataParser? Or does someone else need to do this?

**Comment by jcaraballo17** [comment]
@AmberSJones I am doing that.
