### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#78]
These links from the GAMUT landing pages are not working with the TSA. Is the error with the link itself or with the TSA? The Logan River appears to work, but Provo does not, and Red Butte links to Provo.

Link is on this page in the top right:
![image](https://cloud.githubusercontent.com/assets/5023186/17003207/0bd24f42-4e8c-11e6-9116-9e092ad18591.png)
http://data.iutahepscor.org/mdf/Data/Red_Butte/

http://data.iutahepscor.org/tsa/?network=Provo%20River

**Comment by jcaraballo17** [comment]
Links fixed.

**Comment by AmberSJones** [comment]
Ok- looks good.
