### ISSUE TITLE
Need to update the variables displayed for site landing pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#79]
The variable list for each site's landing page need to be updated. The list of variables is in a Google doc: https://docs.google.com/document/d/1cEpW7cOES3kIXY4uH9nvGkZtCSjp_hUmM5AdCFVGtek/edit

Let me know if you need more information on this. @jcaraballo17 - maybe this is one that @fryarludwig can help out with.

**Comment by jcaraballo17** [comment]
Updated the Data Parser to show get the variables shown in the document.

**Comment by AmberSJones** [comment]
Great.
