### ISSUE TITLE
Add text to RB_KF_BA site

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#80]
This site has been decommissioned. We can keep the landing page, but we should remove the sparkline plots from the page and add this text to the top of the page in red:

"This site was decommissioned on August 8, 2016. Data collection is now occurring at a nearby location (RB_LKF_A)" (link to that site page)

**Comment by horsburgh** [comment]
I agree that we should remove the sparkline plots, but we should maintain a link to the raw data CSV files in HydroShare and a link to the time series analyst where the data can be accessed.

**Comment by AmberSJones** [comment]
Agreed with @horsburgh

**Comment by jcaraballo17** [comment]
Done. Now you can add sites to a list of decommissioned sites to remove the sparkline plots and show this message.

**Comment by AmberSJones** [comment]
@jcaraballo17 , we need to keep the links to the raw data files on the repository (soon to move to HydroShare) as well as a link to the data on the TSA for this site (as well as other decommissioned sites) as @horsburgh mentions. Can you get those back up on the landing page?

**Comment by jcaraballo17** [comment]
Sorry, my bad. Didn't notice I took out the whole section.
It's fixed now.

**Comment by AmberSJones** [comment]
Some strangeness with the alignment:
![image](https://cloud.githubusercontent.com/assets/5023186/18533289/166a4312-7a9f-11e6-929c-ffb1fffe4151.png)

**Comment by jcaraballo17** [comment]
Clear your browser's cache and should be fixed.
