### ISSUE TITLE
Strange files loaded to HydroShare

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#82]
For some sites, there are two files being written to HydroShare for 2016. One of the files has some seemingly random characters appended to the file name, and from the few I checked, it seems like that file contains the more complete data and metadata. The sites for which I noticed it are:
LR_TG_BA
PR_Flood_canal
PR_SageCreek_canal
BSF_CONF_BA
There might be others.

![image](https://cloud.githubusercontent.com/assets/5023186/18559353/27f55622-7b34-11e6-9c21-10ffc780aae5.png)
![image](https://cloud.githubusercontent.com/assets/5023186/18559407/54a2f620-7b34-11e6-98bb-98011fcae726.png)

**Comment by fryarludwig** [comment]
This is how HydroShare handles naming conflicts. This issue and issue #83 have the same cause. I've updated the other issue to reflect what I've done. I don't know the initial cause of this, however it is likely due to using an older version of the iUtahUtilities upload script.

**Comment by AmberSJones** [comment]
Ok. I'm going to close this issue and hope it doesn't crop up again...
