### ISSUE TITLE
Need to link to HydroShare files on site landing pages

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#84]
The HydroShare landing pages for all of the raw GAMUT data are now public and should be linked on each of the site landing pages. I don't know if there is a way to encode the links or if they need to be matched up manually since the title of the resource (with the site code) is not included in the HydroShare url. Here are the resources:

https://www.hydroshare.org/search/?q=&NElat=&NElng=&SWlat=&SWlng=&start_date=&end_date=&selected_facets=subjects_exact:GAMUT

The link replace the link to the ckan site here:
![image](https://cloud.githubusercontent.com/assets/5023186/18560288/2fa6aa20-7b38-11e6-91a8-657b4de7f1a7.png)

**Comment by horsburgh** [comment]
@jcaraballo17 is going to need a lookup table for these. You don't want to use the search link you pasted above. Each resource has an explicit URL that uses its HydroShare identifier. They will look like this:

https://www.hydroshare.org/resource/dd1a2ffbc2e4422682a3fbd552620c32/

**Comment by AmberSJones** [comment]
Right- that's what I meant by manually matching the landing page/site code with the HydroShare url. I can have Abby create a lookup table if that's the best route?

**Comment by horsburgh** [comment]
That would help Juan out.

**Comment by jcaraballo17** [comment]
I can do this manually, it will probably take me 5 minutes to do it.

**Comment by jcaraballo17** [comment]
All links now point to their corresponding hydroshare resource.

**Comment by AmberSJones** [comment]
Haha- sweet, that was supa fast!
