### ISSUE TITLE
New Site

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#86]
We need to add a new site to the website: PR_RW_A.

The data are in the database and there are photos up on Box. 

Who will do this- @fryarludwig or @jcaraballo17 ?

**Comment by fryarludwig** [comment]
I've done the other ones, so it's probably faster for me to take it. I'll let you know if I have any questions.

**Comment by AmberSJones** [comment]
We still need to add the photos for this site to the website, but that is covered by issue #81 , so I will close this issue.
