### ISSUE TITLE
Update Site because of transition to HydroShare (and other updates)

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#87]
Need to update:

Homepage: 
 - [x] Change text: https://docs.google.com/document/d/1m4E31ygXoFX7WWt_FTZ6jJESuaJcDhHXiApuTR1OrlU/edit
 
Software Development: 
 - [x] Remove the sentence under "Software Development.
 - [x] Change text: https://docs.google.com/document/d/12LYwc4OkIcGI_Zb4H6h0Lasvgcomxuy4kjmShHB5Vhw/edit

Data Policy and Publication:
 - [x] Change text: https://docs.google.com/document/d/1zPIV21-NX9wSMgP_pXBJ8D1XRLeNtxh84U4cKmml4RE/edit

 - [x] Under the "Data" menu, change the "Dataset Repository" item to "iUTAH Data on HydroShare" and link to https://www.hydroshare.org/search/?q=&selected_facets=owners_names_exact:iUTAH%20Data%20Manager

 - [x] Under the "Data" menu, add an item "Survey Data" and link to data.iutahepscor.org/surveys

- [x] Personnel: Remove Tony Castronova with (in two places).

- [x] Training Materials: Remove the last two videos (Search & Discovery and Submittal & Publication).

- [x] Documentation: Update text in several places with some new links, too: https://docs.google.com/document/d/10bjsKWS81JzLoFlJORltH_qQAzQcnLSooYEB3VAoMKc/edit#

**Comment by AmberSJones** [comment]
Couple quick things:

We need to change the title of 'Data Repository and Publication System to be 'Data Repository and Publication'. We also need to change the screenshot in that section to the below.
![image](https://cloud.githubusercontent.com/assets/5023186/20723887/7ff727b2-b629-11e6-81b9-419564be0990.png)

We need to remove Mario Matos and Jacob Meline from the Personnel page.

**Comment by AmberSJones** [comment]
A few outstanding items here @jcaraballo17

**Comment by AmberSJones** [comment]
@fryarludwig can you complete this issue?

**Comment by fryarludwig** [comment]
Alright, this should be done.

**Comment by AmberSJones** [comment]
One more thing- I think it's buried above, but we need to remove Mario Matos and Jacob Meline from the Personnel page.

**Comment by fryarludwig** [comment]
I've removed them from the personnel page, and the changes are live.
