### ISSUE TITLE
Links to QC1 HydroShare resources

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#88]
On the site landing pages, we need to add links to the HydroShare QC1 resources associated with each site. These should be a similarly formatted button alongside the 'Download the Raw Data from this Site' button. How about 'Download Quality Controlled Data from this Site'.

**Comment by AmberSJones** [comment]
These need to be updated since the urls for the QC1 resources have changed. @fryarludwig can you work with @jcaraballo17 to get that done?

**Comment by fryarludwig** [comment]
this has been fixed.
