### ISSUE TITLE
New page for real time photo display

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#91]
We need to create a new page under data.iutahepscor.org to display photos taken remotely at several GAMUT sites and streamed to our server. 

The photos stream to this site: http://data.iutahepscor.org/gamutphotos/

We want to access photos from PR_CH_AA, PR_SC_Canal, LR_FB_BA, LR_TWDEF_C, RB_FD_AA, RB_KF_BA, and perhaps a few other sites that I will let you know about.

We only want to display the most recent photo. Below is my sketch of how we want this page to look. The boxes are thumbnails of photos, which clicking on them brings up a larger photo in its own page or in a gallery window.

What other information do you need?

**Comment by AmberSJones** [comment]
![img_1026](https://cloud.githubusercontent.com/assets/5023186/20725477/2ddd9320-b62f-11e6-870f-c2b09ed0f463.JPG)

**Comment by AmberSJones** [comment]
We also need to add a map to the page- a simple Google map similar to those on the site landing pages with pins for each site that has photos. When the pin is clicked on, it brings up the photo.

**Comment by fryarludwig** [comment]
This has been completed, any further changes we need to make can be separate issues.
