### ISSUE TITLE
Another New Site

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#92]
We have another new site for which we need a new site landing page and new HydroShare resource for data. The site is PR_HD_AA.

@fryarludwig , can you address this?

**Comment by AmberSJones** [comment]
Just a reminder that this still needs to be done.

**Comment by fryarludwig** [comment]
The site has been added, but there are no site images for this yet. Is there any way to get these before I update the live website?

**Comment by AmberSJones** [comment]
Do you have access to the box folder where the images are stored? There are images for that site there. You will also need to access that folder to work on the other issue that pertains to site photos.

**Comment by AmberSJones** [comment]
Here's the link: https://usu.box.com/s/o8spx2xjk62qpyebusa573mlslqqr1rx

**Comment by fryarludwig** [comment]
This is done
