### ISSUE TITLE
Add Tutorial Videos and Instructions to Website

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#93]
We need to add some content to the website.
On this page, http://data.iutahepscor.org/mdf/About/Training_Materials/:
- [x] Change "Data Publication Tutorials" to "Introduction to Data Publication".
- [x] Add new section: "HydroShare for Data and Model Sharing and Publication". Add two videos that are on the Google drive. The text below should be: "**Getting Started and Creating a Resource in HydroShare:** HydroShare is repository for sharing, collaborating around, and formally publishing scientific data. Data and models are organized as resources." and "**Sharing and Publishing Resources in HydroShare:** Resources can be shared publicly or with individuals or groups with specific permissions levels. HydroShare can also be used for formal publication of data."
- [x] Add a sentence "See this page for step-by-step instructions on sharing and publishing iUTAH data and models to HydroShare." with a link to http://iutahepscor.org/data_modeling/hydroshare_steps.shtml.
- [x] Change the title "QAQC Training" to "Sensor Data Management Training".
- [x] Remove this sentence: "This page provides links to training materials that have been prepared by the iUTAH CI Team."

--------------------------------------------
- [x] On the homepage, in the "Data Publication in HydroShare" section, add the sentence "View tutorials on data publication in HydroShare" with a link to the tutorials.

- [x] On this page, http://data.iutahepscor.org/mdf/Data/Data_Policy/, under "Data Publication with HydroShare", we could either add a sentence at the end of the paragraph: "View tutorials on data publication in HydroShare" with a link to the tutorials OR we could also put the tutorials here. @horsburgh and @fryarludwig, what do you think?

- [x] On this page, http://data.iutahepscor.org/mdf/Data/Data_Policy/, under "Data Publication with HydroShare", add a sentence "See this page for step-by-step instructions on sharing and publishing iUTAH data and models to HydroShare." with a link to http://iutahepscor.org/data_modeling/hydroshare_steps.shtml.

**Comment by fryarludwig** [comment]
For your second-to-last bullet point, I added the following at the end of the paragraph:
 Video tutorials on data publication in HydroShare are available on our Training Materials page.

**Comment by fryarludwig** [comment]
Feel free to suggest any changes to my implementations of these features, otherwise we can close this issue.

**Comment by AmberSJones** [comment]
Great. Just one thing: This sentence should go below "HydroShare for Data and Model Sharing and Publication" (above the Tutorial Videos): 

See this page for step-by-step instructions on sharing and publishing iUTAH data and models to HydroShare.

**Comment by fryarludwig** [comment]
Ah, gotcha. This is done, I'll have it live by the end of the day.
