### ISSUE TITLE
Show position in photo slider

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUTAHData#95]
Implement a way to show the current position in the photo slider. I imagine that this would be some sort of highlight around the box of the current photo.

**Comment by fryarludwig** [comment]
Completed - let me know if you want it adjusted at all.

**Comment by AmberSJones** [comment]
I think the outline could be thicker/bolder.

**Comment by fryarludwig** [comment]
Made it a bit bolder and added a subtle shadow.

**Comment by AmberSJones** [comment]
Great.
