### ISSUE TITLE
Differentiate between active and inactive sites on GAMUT Webcam page

### ISSUE THREAD

**Issue by fryarludwig** [UCHIC/iUTAHData#99]
Some of the sites with photos displayed on our GAMUT Webcams page are inactive and have no recent images. We need to have a visual indicator that differentiates between the sites with active webcam images and sites that are inactive.

**Comment by fryarludwig** [comment]
Currently any site with no new photos within the last two weeks will be marked inactive automatically. Is there another time range you would prefer, and/or would you prefer to manage the active/inactive designations manually?

**Comment by AmberSJones** [comment]
Two weeks seems reasonable to me. I can see a few cases where we might want to manually designate site's status, but I don't want to be responsible for manually managing active/inactive, so I say stick with the two week threshold. Should this be closed?
